debugging dns problem

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -21,6 +21,12 @@ jobs:
           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
           echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+      - name: check available tools
+        run: |
+          which getent || echo "getent NOT found"
+          which curl || echo "curl NOT found"
+          which nslookup || echo "nslookup NOT found"
+          which dig || echo "dig NOT found"
       - name: debug dns config
         run: |
           cat /etc/resolv.conf
